apply plugin: 'com.android.application'

android {
	namespace "org.vita3k.emulator"
	compileSdk 34
	ndkVersion "26.3.11579264"
	buildFeatures {
		buildConfig true
	}

	defaultConfig {
		applicationId "org.vita3k.emulator"
		minSdk 24
		targetSdk 34
		versionCode 12
		versionName "0.2.0-12"

		externalNativeBuild {
			cmake {
				abiFilters.addAll( 'arm64-v8a' )
			}
		}
	}

	signingConfigs{ null}
		
	

	buildTypes {
         release {
          signingConfig null
          }
	}
	

	sourceSets {
		main {
			jniLibs.srcDirs = ['prebuilt']
			assets {
				srcDirs 'assets'
			}
		}
	}

	externalNativeBuild {
		cmake {
			path '../CMakeLists.txt'
			version '3.22.1+'
		} 
	}

    buildFeatures {
		viewBinding true
	}
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
	implementation 'androidx.appcompat:appcompat:1.6.1'
	implementation "androidx.core:core:1.12.0"
	implementation 'androidx.core:core-google-shortcuts:1.1.0'
	implementation 'com.google.android.material:material:1.11.0'
	implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
	implementation 'com.getkeepsafe.relinker:relinker:1.4.5'
	implementation 'com.jakewharton:process-phoenix:2.1.2'
}
